#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = ["moviepy>=2.0", "google-genai", "pillow"]
# ///
"""
Extract a frame from video and use Gemini to add a Red Bull logo to Michael's suit.
"""

import os
import base64
from pathlib import Path
from moviepy import VideoFileClip
from google import genai
from google.genai import types
from PIL import Image
import io

# Configuration
VIDEO_FILE = "office.mp4"
TIMESTAMP = 86  # 1:26 in seconds (slightly later to avoid transition)
OUTPUT_DIR = "edited_frames"

def extract_frame(video_path: str, timestamp: float) -> Image.Image:
    """Extract a frame from video at the given timestamp."""
    print(f"📸 Extracting frame at {timestamp//60:.0f}:{timestamp%60:02.0f}...")
    
    video = VideoFileClip(video_path)
    frame = video.get_frame(timestamp)
    video.close()
    
    # Convert numpy array to PIL Image
    image = Image.fromarray(frame)
    return image

def add_logo_with_gemini(image: Image.Image, prompt: str) -> Image.Image:
    """Use Gemini to edit the image with the given prompt."""
    print("🎨 Sending to Gemini for editing...")
    
    # Initialize client
    client = genai.Client()
    
    # Convert PIL image to bytes for the API
    img_byte_arr = io.BytesIO()
    image.save(img_byte_arr, format='PNG')
    img_bytes = img_byte_arr.getvalue()
    
    # Create the image part
    image_part = types.Part.from_bytes(
        data=img_bytes,
        mime_type='image/png',
    )
    
    # Generate with image editing using Gemini 3 Pro
    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=[image_part, prompt],
    )
    
    # Extract the generated image from response
    for part in response.parts:
        if part.inline_data is not None:
            print("✅ Got edited image from Gemini!")
            # Decode the base64 image data
            image_data = part.inline_data.data
            edited_image = Image.open(io.BytesIO(image_data))
            return edited_image
        elif part.text is not None:
            print(f"📝 Gemini says: {part.text}")
    
    raise ValueError("No image was generated by Gemini")

def main():
    print("=" * 60)
    print("🏷️  ADD RED BULL LOGO TO MICHAEL'S SUIT")
    print("=" * 60)
    
    # Check video exists
    if not Path(VIDEO_FILE).exists():
        print(f"❌ Video not found: {VIDEO_FILE}")
        return
    
    # Create output directory
    Path(OUTPUT_DIR).mkdir(exist_ok=True)
    
    # Extract frame
    original_frame = extract_frame(VIDEO_FILE, TIMESTAMP)
    original_path = Path(OUTPUT_DIR) / "original_frame_1_26.png"
    original_frame.save(original_path)
    print(f"💾 Original frame saved: {original_path}")
    
    # Define the editing prompt
    prompt = """
    Using this image, add a Red Bull logo to Michael Scott's suit jacket. 
    Place the logo on the left breast pocket area of his suit, as if it were 
    a sponsor patch or embroidered logo. Make it look natural and realistic, 
    like an actual sponsor logo on his suit. Keep everything else in the 
    image exactly the same - his face, expression, the background, and all 
    other details should remain unchanged.
    """
    
    try:
        # Edit with Gemini
        edited_frame = add_logo_with_gemini(original_frame, prompt)
        
        # Save edited frame
        edited_path = Path(OUTPUT_DIR) / "michael_with_redbull_1_26.png"
        edited_frame.save(edited_path)
        print(f"💾 Edited frame saved: {edited_path}")
        
        print("\n✅ Done! Check the edited_frames folder.")
        
    except Exception as e:
        print(f"❌ Error during Gemini editing: {e}")
        raise

if __name__ == "__main__":
    main()

